In [3]:
import tensorflow as tf
from keras import backend as K

a = tf.constant([[1,2],[3,4]])
b = tf.constant([[1,2],[3,4]])

a = K.flatten(a);
b = K.flatten(b);

print(a,b)

print(a*b)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([ 1  4  9 16], shape=(4,), dtype=int32)
